package t;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>t</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("t") 
@Runtime(CRuntime.class) 
public class TLibrary {
	static {
		BridJ.register();
	}
	/**
	 * Original signature : <code>Foo* CreateFoo(char*)</code><br>
	 * <i>native declaration : /Users/ochafik/t.h:2</i>
	 */
	public static Pointer<Foo > CreateFoo(Pointer<Byte > charPtr1) {
		return (Pointer)Pointer.pointerToAddress(CreateFoo(Pointer.getPeer(charPtr1)), Foo.class);
	}
	@Ptr 
	protected native static long CreateFoo(@Ptr long charPtr1);
}
